name: twinkstar
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  file_picker: ^5.2.4
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  flutter_signin_button: ^2.0.0
  flutter_zoom_drawer: ^3.0.3
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^9.0.0
  get: ^4.6.5
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^2.1.0
  rename: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
